### ISSUE TITLE
Suggestions by Q Team

### ISSUE THREAD

**Issue by schultkr** [QuantLet/BCS#4]
Readme-Auto-Creation – 2. Iteration.

Folgende Mängel/Details:

2) https://github.com/QuantLet/BCS/tree/master/BCS_KernelDAX

Das Bild ist „beschnitten“, Bandwidth = 0.00 ??

Updaten und Bescheid geben

3) https://github.com/QuantLet/BCS/tree/master/BCS_NormalCopula

Das Bild ist ungünstig, die 5 Teilbilder sind winzig.

Kann man nicht alle 5 Plots als einzelne Bilder zur Verfügung stellen?

**Comment by schultkr** [comment]
Anna for the Pictures you just have to use the quantlet BCS_NormalCopula step by step.
 Run the code until the first Picture Export it and then use graphics.off()
 do the same for the next one and so on.

use 480 \* 480 Pixel as Format.

**Comment by schultkr** [comment]
did 1) https://github.com/QuantLet/BCS/tree/master/BCS_BinormalDensity

Metainfo: Name of Quantlet : BCS_NormalDensity

BCS_BinormalDensity.r

Pfad: https://github.com/QuantLet/BCS/tree/master/BCS_BinormalDensity

**Comment by Palindroma** [comment]
![bcs_normalcopula1](https://cloud.githubusercontent.com/assets/16956533/12936244/440c0682-cf9d-11e5-9d52-9c3f20b2a7f4.png)

**Comment by Palindroma** [comment]
![bcs_normalcopula2](https://cloud.githubusercontent.com/assets/16956533/12936299/d4e1d8ee-cf9d-11e5-92e5-06afbc5f5df1.png)

**Comment by Palindroma** [comment]
![bcs_normalcopula3](https://cloud.githubusercontent.com/assets/16956533/12936309/db824dfa-cf9d-11e5-9f13-6ac4f9636d40.png)

**Comment by Palindroma** [comment]
![bcs_normalcopula4](https://cloud.githubusercontent.com/assets/16956533/12936319/ec97e9ec-cf9d-11e5-9cf5-3a364f6a2218.png)

**Comment by Palindroma** [comment]
![bcs_normalcopula5](https://cloud.githubusercontent.com/assets/16956533/12936322/f3acb820-cf9d-11e5-9b5a-e27e5586a0ed.png)

**Comment by Palindroma** [comment]
![rplot](https://cloud.githubusercontent.com/assets/16956533/12936325/faef697a-cf9d-11e5-964c-e8f616cb4be1.png)

**Comment by schultkr** [comment]
Good upload them.

**Comment by Palindroma** [comment]
BCS_NormalColula, BCS_BInhist, BCS_NormPdfCdf, tQQ  png plots new
